### ISSUE TITLE
set axes limits for each graphs generated with geom_facet 

### ISSUE THREAD

**Issue by chamaelj** [ARTbio/tools-artbio#130]
https://github.com/chamaelj/tools-artbio/blob/1c915a0e9d2ffb17b54e5073a88e977ea5240697/tools/small_rna_map/test.r#L9

In my dataframe " Table", i have a column "Chrom_length" which containe the xlim value of every graph. But when i add this code to fix the limit of x axes:
`+xlim(0,Table$Chrom_length)` i have this error:   _length(lims) == 2 is not TRUE_
When I tried whith     `scale_x_continuous(limits=c(0,Table$Chrom_length))`
I have this error: _Error in zero_range(range) : x must be length 1 or 2._

How can i set the limit of my axis for each graph?

**Comment by drosofff** [comment]
In both cases I would say that there is a dimension issue:

When you state `xlim(0,Table$Chrom_length)`, 0 is a scalar or if you prefer a vector of length 1, whereas Table$Chrom_length is a vector with dimension equal to the number of chromosomes.
No guaranty, but you may test: `xlim(rep(0, length(Table$Chrom_length)),Table$Chrom_length)`
