### ISSUE TITLE
How to separate small RNA reads that show 10nt overlap using signature.py

### ISSUE THREAD

**Issue by juulluu21** [ARTbio/tools-artbio#148]
Is there any way that after running the _signature.py_ script, I can get the reads that produce a specific overlap (for example I want to get all the reads that are overlapping by 10nt)?

Thanks!

**Comment by juulluu21** [comment]
Is there anyone who has assigned to do this? Or at least, is it possible to do?
Thanks.

**Comment by drosofff** [comment]
@juulluu21 with the last update of signatures tool (PR #176), it will be easier to address the need !
I would favor a separate tool such as `overlapping reads`

**Comment by juulluu21** [comment]
@drosofff: thank you very much. The command I run the script is:
signature.py  input.sam  min_length   max_length    min_overlap    max_overlap  output.txt

To get the overlapping (10nt overlap) reads (all sizes), how the command would look like.
Sorry for the novice question.

**Comment by drosofff** [comment]
@juulluu21 it will be something like:

`overlapping_reads.py input.sam min_length max_length min_overlap max_overlap output.fa(stq)`... but I can't really answer before coding the tool ;-)

**Comment by juulluu21** [comment]
Hahaha.....

**Comment by drosofff** [comment]
@juulluu21 see the PR #191 and the argparse instance in the python code for direct use of the python code. Test is welcome before pushing the tool in the toolshed !
Note that for in line python run, the bam file must be next to the index (.bai) for proper use of the pysam module.

**Comment by juulluu21** [comment]
Thank you very very much. I have used the script. I used this command in mac terminal:

python overlapping_reads.py  --input  xxx.sorted.bam   --minquery  26    --maxquery  26  --mintarget  22  --maxtarget  22  --overlap 10   --output xxx.fastq

Output:
This is (below) what I got in the output file. It seems a fasta file instead of fastq. I expected that the output file would contain only 26 and 22nt reads. But, it has different sizes reads (26-31nt). Is the command that I am using is wrong?


>scaffold_1|7774354|R|26
TCCGTCTGAAGTTGATGAACCTGATG
>scaffold_1|7769043|R|26
TAATGACAAAAAATCTTGAGTGGACT
>scaffold_1|7570282|R|30
TAGGACGTAAGCTACATTAGAATGTCAACA
>scaffold_1|7570282|R|30
TAGGACGTAAGCTACATTAGAATGTCAACA
>scaffold_1|7570282|R|30
TAGGACGTAAGCTACATTAGAATGTCAACA
>scaffold_1|7570282|R|30
TAGGACGTAAGCTACATTAGAATGTCAACA
>scaffold_1|7570282|R|30
TAGGACGTAAGCTACATTAGAATGTCAACA
>scaffold_1|7570282|R|30
TAGGACGTAAGCTACATTAGAATGTCAACA
>scaffold_1|7570282|R|30
TAGGACGTAAGCTACATTAGAATGTCAACA
>scaffold_1|7570282|R|30
TAGGACGTAAGCTACATTAGAATGTCAACA
>scaffold_1|7570285|R|27
TAGGACGTAAGCTACATTAGAATGTCA
>scaffold_1|7570285|R|27
TAGGACGTAAGCTACATTAGAATGTCA
>scaffold_1|7570285|R|27
TAGGACGTAAGCTACATTAGAATGTCA
>scaffold_1|7570285|R|27
TAGGACGTAAGCTACATTAGAATGTCA
>scaffold_1|7570286|R|26
TAGGACGTAAGCTACATTAGAATGTC
>scaffold_1|7570286|R|26
TAGGACGTAAGCTACATTAGAATGTC
>scaffold_1|7570286|R|26
TAGGACGTAAGCTACATTAGAATGTC

**Comment by drosofff** [comment]
Well, I reopen the issue...

- it's true, the output is fasta. Did I say something else ? The name that you provide for the parameter does not has the ability to change the method...

- You tested the case of "asymetric" pairing (target 22, query 26) which is not covered yet well by the script (I new it but I forgot). In addition, your output clearly show that there is another part of the code to fix, thanks for testing !

**Comment by juulluu21** [comment]
A .fasta output would be ok for me. 

Well, I also tried symmetric pairing (22 and 22). I got the same type of output (mix of several size categories).

Thanks!!

**Comment by drosofff** [comment]
@juulluu21 Let's see if the PR #192 is more convincing (I think so). You are welcome to test this new version with your datasets. In the meantime I have to clean a bit the current code.

**Comment by juulluu21** [comment]
I have used PR #192 and got this in terminal::

Traceback (most recent call last):
  File "/Users/Alex/Desktop/aaaaa.py", line 155, in <module>
    args.maxtarget, args.output, args.overlap)
  File "/Users/Alex/Desktop/aaaaa.py", line 147, in main
    mapobj = Map(input)
  File "/Users/Alex/Desktop/aaaaa.py", line 39, in __init__
    self.all_query_positions = self.query_positions(self.bam_object)
  File "/Users/Alex/Desktop/aaaaa.py", line 59, in query_positions
    list(set(all_query_positions[chrom])))
TypeError: '<' not supported between instances of 'NoneType' and 'int'


Is it possible then when I copy the script and paste in text editor like textWrangler or Vim they are messing up the script?

Can I just get the downloadable file?
Thanks.

**Comment by drosofff** [comment]
`wget https://raw.githubusercontent.com/ARTbio/tools-artbio/96ed5824190aff281cc3aa47dc60fc66aac41db3/tools/small_rna_signatures/overlapping_reads.py`

You"ll need also the get the pysam module loaded in you python env

**Comment by juulluu21** [comment]
**Command:**
_python2    overlapping_reads.py   --input  XXX.sorted.bam   --minquery  26    --maxquery  26 --mintarget  26 --maxtarget  26 --overlap 10  --output xxxout.fasta_

**Output:**
_Traceback (most recent call last):
  File "/Users/Alex/overlapping_reads.py", line 155, in <module>
    args.maxtarget, args.output, args.overlap)
  File "/Users/Alex/overlapping_reads.py", line 149, in main
    output, overlap)
  File "/Users/Alex/overlapping_reads.py", line 71, in direct_pairing
    start=pos, end=pos+overlap-1)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'_

****I am not sure why this did not work. When I used signature.py, it clearly showed 10nt overlap.**  This file was generated on a relatively small datasets.** 

**I ran the script on other files, which were quite bigger files:**

 _python2    /Users/Alex/overlapping_reads.py   --input  YYY.sorted.bam    --minquery  26    --maxquery  26 --mintarget  26 --maxtarget  26 --overlap 10  --output    yyyout.fasta_

**It worked!**


 _python2    /Users/Alex/overlapping_reads.py   --input  ZZZ.sorted.bam    --minquery  18    --maxquery  32 --mintarget  18 --maxtarget  32 --overlap 10  --output zzzout.fasta_

**It also worked!**

**However, the output fasta files are very small. I am attaching them here (I have changed the file type for uploading)**

[zzzout.txt](https://github.com/ARTbio/tools-artbio/files/1279474/zzzout.txt)
[yyyout.txt](https://github.com/ARTbio/tools-artbio/files/1279475/yyyout.txt)

****I am not sure if the output is masked somehow. Seems I am loosing lot of reads.

Thank you very much!!!****

**Comment by drosofff** [comment]
> TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
> 
> I am not sure why this did not work. When I used signature.py, it clearly showed 10nt overlap. This file was generated on a relatively small datasets.

Well, well, well... me neither !

If XXX.sorted.bam is small, can you send it for closer inspection ?

Also, do you know the pysam version that is launched in your python2 environment ?

**Comment by juulluu21** [comment]
**Its pysam-0.12**

I uninstall and install back python3 with pysam-0.12 but same problem.

XXX.sorted.bam file is 290 Mb. Is there a way that I can send that file?

If the script is working just fine for you, it is possible that I have messed up some installation things.....(python2, python, python3, pysam.........very confusing for me (!!!). There are so many options people are saying in internet.......)

I am using ‎OS X Yosemite 10.10.5. Just now, I tried to install python following this:
https://wsvincent.com/install-python3-mac/

Its same result for XXX.sorted.bam

**Comment by drosofff** [comment]
Why not trying the tool in our Galaxy server: https://mississippi.snv.jussieu.fr/root?tool_id=toolshed.g2.bx.psu.edu/repos/artbio/small_rna_signatures/overlapping_reads/0.9.2
You've just to register and upload the bam file, should be quick !

FYI, the tool is tested in this repo (Travis) with pysam 0.11.2.1 in python 2.7. See for instance https://travis-ci.org/ARTbio/tools-artbio/jobs/271127785#L1656

**Comment by juulluu21** [comment]
**I have tried in Galaxy.** 

_Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/home/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/artbio/small_rna_signatures/4d9682bd3a6b/small_rna_signatures/overlapping_reads.py", line 155, in <module>
    args.maxtarget, args.output, args.overlap)
  File "/home/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/artbio/small_rna_signatures/4d9682bd3a6b/small_rna_signatures/overlapping_reads.py", line 149, in main
    output, overlap)
  File "/home/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/artbio/small_rna_signatures/4d9682bd3a6b/small_rna_signatures/overlapping_reads.py", line 71, in direct_pairing
    start=pos, end=pos+overlap-1)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'_

**Comment by drosofff** [comment]
More and more interesting.... I'll have a close look and I come back here...

**Comment by juulluu21** [comment]
I am very sorry for all these troubles.....

**Comment by drosofff** [comment]
don't. This is how code is eventually working !

**Comment by juulluu21** [comment]
Thanks!!!

**Comment by drosofff** [comment]
Here we are @juulluu21 
The PR #200 fixes the bug with your dataset XXX.sorted.bam. This was a misuse of the pysam module (whose documentation lacks often appropriate warnings, for my defense...).

Yet, for this dataset, I noticed that it takes more than 12 hours to get the result.

I hope improving the core algorithm of the script in the next versions. I now that there is room for this.

Thank you very much for your tests. It really helps !

**Comment by juulluu21** [comment]
Thank you very much. Good to hear that my data was helpful to fix the problems....I am waiting to get the new code. Making it memory efficient would be great because I have so many files to work on.....

Cheers!

**Comment by drosofff** [comment]
@juulluu21, the PR #201 is expected to improve (greatly) the performance of the tool.
Note also that, more satisfactorily, the algorithm is now symmetric, ie looking at 20-22nt / 23-29nt pairs is equivalent to looking at 23-29nt / 20-22nt pairs.
This version of the tools will be soon pushed in the main toolshed and upgraded in mississippi.

**Comment by drosofff** [comment]
The improvement is about x70 !
I close the issue and hope not to reopen it ;-)
