### ISSUE TITLE
Push qr_coder in the testtoolshed

### ISSUE THREAD

**Issue by drosofff** [ARTbio/tools-artbio#18]
@fabiorjvieira @mvdbeek 
given https://github.com/ARTbio/tools-artbio/blob/master/tools/qr_coder/.shed.yml#L13 , why qr_coder is not pushed in the testoolshed ?

**Comment by fabiorjvieira** [comment]
@drosofff drosofff https://testtoolshed.g2.bx.psu.edu/ is testoolshed, right? So, it is done.

**Comment by drosofff** [comment]
Yes it's there now. Why not before give the line in the .yml file ?

**Comment by fabiorjvieira** [comment]
@drosofff It was not created before, because I executed --shed_target only on my local tool shed (and in lbcd41), my dear Watson. ;)
