### ISSUE TITLE
mature_mir_gff_translation.py error

### ISSUE THREAD

**Issue by ccedmendoza** [ARTbio/tools-artbio#246]
When using mature_mir_gff_translation.py on a Bos Taurus gff there is a bug:

+ Get mirbase gff: `wget --quiet ftp://mirbase.org/pub/mirbase/CURRENT/genomes/bta.gff3`
+ Translate it: python `mature_mir_gff_translation.py --input bta.gff3 --output trad_bta.gff`

This is the error: the start and end positions of D=MIMAT0011961_1

+ `grep "bta-miR-2404" trad_bta.gff`
> bta-miR-2404	.	miRNA	45	64	.	-	.	ID=MIMAT0011961;Alias=MIMAT0011961;Name=bta-miR-2404;Derives_from=MI0011446;Parent_mir_Name=bta-mir-2404-1
bta-miR-2404	.	miRNA	**-5098241**	**-5098222**	.	+	.	**ID=MIMAT0011961_1**;Alias=MIMAT0011961;Name=bta-miR-2404;Derives_from=MI0011446;Parent_mir_Name=bta-mir-2404-1
bta-miR-2404	.	miRNA	46	65	.	-	.	ID=MIMAT0011961_2;Alias=MIMAT0011961;Name=bta-miR-2404;Derives_from=MI0011535;Parent_mir_Name=bta-mir-2404-2

I think the problem comes from the mirbase gff:

There are 2 miRNA deriving from **MI0011446** one in chr17 and the other in chr29. But there is only one miRNA primary transcript with that ID in chr17, in chr29 the ID is **MI0011446_2**.

+ `grep "MI0011446" bta.gff3`
>chr17	.	miRNA_primary_transcript	6163842	6163906	.	-	.	**ID=MI0011446**;Alias=MI0011446;Name=bta-mir-2404-1
chr17	.	miRNA	6163886	6163905	.	-	.	ID=MIMAT0011961;Alias=MIMAT0011961;Name=bta-miR-2404;**Derives_from=MI0011446**
chr29	.	miRNA_primary_transcript	1065599	1065663	.	+	.	**ID=MI0011446_2**;Alias=MI0011446;Name=bta-mir-2404-1
chr29	.	miRNA	1065600	1065619	.	+	.	ID=MIMAT0011961_1;Alias=MIMAT0011961;Name=bta-miR-2404;**Derives_from=MI0011446**

**Comment by drosofff** [comment]
With the new mirbase v22 release it has become clear that some gff3 entries must be skipped during gff parsing:

miRNA_primary_transcript with ID in the form of `ID=MI0033427_2` with an underscore should be skipped, in particular because these features are **not present in the hairpin.fa file from mirbase

miRNA with ID in the form of `ID=MIMAT0041637_1` with a MIMA suffix and and underscore "belong" sur miRNA_primary_transcript described above and should be similarly skipped

**Comment by drosofff** [comment]
Another issue is with the gff formatting of mirbase v19.
to be parsed as v20 and latter, I will locally reformat the v19 gff3s as follows:

MI(\d+)_1 become MI(\d+)
The other MI(\d+)_[23456789] stay unchanged

MIMAT(\d+)_1 become MIMAT(\d+)
The other MIMAT(\d+)_[23456789] are decremented by 1 -->  MIMAT(\d+)_[12345678]

**Comment by drosofff** [comment]
This can probably be closed

**Comment by ccedmendoza** [comment]
ok
