### ISSUE TITLE
small_RNA_maps has pdf construction problems

### ISSUE THREAD

**Issue by ccedmendoza** [ARTbio/tools-artbio#250]
It is used in the new version of the metavisitor workflows and when using the workflow for remapping in Use Cases 1–1,2,3 the output pdf is the following:
[Galaxy26-[small_RNA_maps].pdf](https://github.com/ARTbio/tools-artbio/files/1578682/Galaxy26-.small_RNA_maps.pdf)

As we can see the first plot has no title and globally speaking the pdf's top and bottom was cropped. Finally there are plots missing (we should have 2 plots for each file and there are 5 files)
This is the original workflow's [output](http://journals.plos.org/plosone/article/figure/image?size=large&id=info:doi/10.1371/journal.pone.0168397.g002)

**Comment by drosofff** [comment]
Poke @ccedmendoza

**Comment by ccedmendoza** [comment]
This issue was resolved
