### ISSUE TITLE
sequence_format_converter's test data are sorted

### ISSUE THREAD

**Issue by ccedmendoza** [ARTbio/tools-artbio#258]
example:

*fastqTofasta.sorted.fa*

>...
\>96
\>97
\>98
\>99
AATGGCACTGGAAGAATTCACGG
AATGGCACTGGAAGAATTCACGG
AATGGCACTGGAAGAATTCACGGG
AATGGCACTGGAAGAATTCACGGG
...

**Comment by drosofff** [comment]
So what ? :-)

**Comment by ccedmendoza** [comment]
No issue
