### ISSUE TITLE
RSEM Bowtie2 Reference Name attribute not adapted

### ISSUE THREAD

**Issue by lldelisle** [ARTbio/tools-artbio#295]
Hi,
Thank you very much for the rsem wrapper. However, when I am using a name for the reference name, the files are created with this name but the attribute Reference Name seems to stay the same: rsem_bt2_ref. Thus, when I try to reuse the reference, the command line launch is:
ln -f -s '/slipstream/galaxy/production/data/files/043/dataset_43720.dat' 'uncomp_single.fastq' && rsem-calculate-expression --seed-length 25 --forward-prob 0 --num-threads ${GALAXY_SLOTS:-4} --bowtie2 --sort-bam-by-coordinate --output-genome-bam  --phred33-quals uncomp_single.fastq /slipstream/galaxy/production/data/files/069/dataset_69790_files/**rsem_bt2_ref** rsem_output > /slipstream/galaxy/production/data/files/070/dataset_70040.dat
whereas expected
ln -f -s '/slipstream/galaxy/production/data/files/043/dataset_43720.dat' 'uncomp_single.fastq' && rsem-calculate-expression --seed-length 25 --forward-prob 0 --num-threads ${GALAXY_SLOTS:-4} --bowtie2 --sort-bam-by-coordinate --output-genome-bam  --phred33-quals uncomp_single.fastq /slipstream/galaxy/production/data/files/069/dataset_69790_files/**mm10_filtered_92** rsem_output > /slipstream/galaxy/production/data/files/070/dataset_70040.dat
https://github.com/ARTbio/tools-artbio/blob/bc1a0a07c92b46f55e1018abc9e011214d34fc2d/tools/rsem/rsem-bwt2.xml#L147
and then I got an error because 
Cannot open /slipstream/galaxy/production/data/files/069/dataset_69790_files/rsem_bt2_ref.grp! It may not exist.
Whereas : /slipstream/galaxy/production/data/files/069/dataset_69790_files/mm10_filtered_92.grb exists...

Thank you,

Lucille

**Comment by lldelisle** [comment]
Sorry, I needed to restart my instance to have the new datatype installed correctly.
Solved.

**Comment by drosofff** [comment]
I like when issues are solved that way ![bitmoji](https://render.bitstrips.com/v2/cpanel/29c5dd71-0876-4f5f-ab95-339aa404a64a-f25ea1c3-13f9-4eca-a3db-0b5a0028d382-v1.png?transparent=1&palette=1&width=246)
