### ISSUE TITLE
SrBowtie tools has an issue with outputs when input data are fastq files

### ISSUE THREAD

**Issue by drosofff** [ARTbio/tools-artbio#298]
in https://github.com/ARTbio/tools-artbio/blob/master/tools/sr_bowtie/sRbowtie.xml#L127, we did a conditional change of the output format since when the input is fastq, bowtie return aligned and unaligned reads in a fastq format too (not fasta)

**Comment by ccedmendoza** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SrBowtie tools has an issue with outputs when input data are fastq files](https://trello.com/c/g3evKdGl/368-srbowtie-tools-has-an-issue-with-outputs-when-input-data-are-fastq-files)

**Comment by ccedmendoza** [comment]
This issue was resolved #302
