### ISSUE TITLE
Concatenate tool could be improved

### ISSUE THREAD

**Issue by ccedmendoza** [ARTbio/tools-artbio#329]
**Is your feature request related to a problem? Please describe.**

Now that the embedded lists are more often used in galaxy, when concatenating datasets from embedded lists we can't select at which level of the list the datasets will be concatenates.

**Describe the solution you'd like**

I would like to be able to select the type of concatenation I wish to perform (e.i. when I have a paired list, do I wish to concatenate all my datasets and have a single final output? Do I wish to concatenate all forward and then all reverse and have a single paired dataset as output? etc...)

**Describe alternatives you've considered**

**Additional context**

**Comment by drosofff** [comment]
Sounds good @ccedmendoza but double check that similar toos by other (gruening, mvdbeek, devteam) have not improved to take into account these "new" use cases.

**Comment by drosofff** [comment]
shall we close the issue @ccedmendoza ?

**Comment by ccedmendoza** [comment]
yes I believe it has been improved 👍
