### ISSUE TITLE
Register repository at https://github.com/galaxyproject/planemo-monitor ?

### ISSUE THREAD

**Issue by mvdbeek** [ARTbio/tools-artbio#333]
**Is your feature request related to a problem? Please describe.**
planemo-monitor checks galaxy tools with multiple dependencies, builds a docker container for these tools and uploads them to https://quay.io/
This really fixes the dependencies used and allows running tools in docker, kubernetes, singularity etc.

**Describe the solution you'd like**
You would just have to add tools-artbio to one of the repositories_N.yml files in https://github.com/galaxyproject/planemo-monitor

**Comment by drosofff** [comment]
Great ! Thanks @mvdbeek for the info !
