### ISSUE TITLE
QR coder tool_dependencies.xml break shed_lint

### ISSUE THREAD

**Issue by mvdbeek** [ARTbio/tools-artbio#35]
@fabiorjvieira 
Can you make planemo shed_lint pass on qr_coder?
You have 2 unnecessary `-->` in the xml.

**Comment by fabiorjvieira** [comment]
Extra "-->" removed, please see https://github.com/ARTbio/tools-artbio/pull/36.

**Comment by drosofff** [comment]
At some point we should either change the owner of this tool or get the write rights to maintain the tools

**Comment by drosofff** [comment]
writable for drosofff@gmail.com
