### ISSUE TITLE
Adapter sequence in YAC_clipper should accommodate Capitals or small letters

### ISSUE THREAD

**Issue by drosofff** [ARTbio/tools-artbio#4]
Either filter entry by upgrading the XML tool form, or capitalize the adapter string in the python code in https://github.com/ARTbio/tools-artbio/tree/master/tools/yac_clipper

**Comment by mvdbeek** [comment]
I prefer capitalizing in python, should be more universal.

**Comment by drosofff** [comment]
Anyway I am noising for nothing: the adapter is already capitalized with .upper() method.
