### ISSUE TITLE
Improvement gsc_high_dim_visu

### ISSUE THREAD

**Issue by bellenger-l** [ARTbio/tools-artbio#401]
- allow numeric factor for cell coloration based on : 
    - a score thanks to a two columns table
    - gene expression by looking directly in the expression matrix (be careful, if raw count matrix maybe log transformed the data)
- plot PC1 vs PC2 - PC1 vs PC3 - PC2 vs PC3
- add axis labels for t-SNE
- remove unnecessary parameter : normalize 
- output cluster table
- add clusterR utility to get external validation of clustering (only if the factor table is given & is not numerical)

--> Done : #405

**Comment by bellenger-l** [comment]
Add UMAP visualisation ?

**Comment by drosofff** [comment]
Sure, but in a new issue. In CI, what is done is done

**Comment by bellenger-l** [comment]
Ok !
