### ISSUE TITLE
improve gsc_mannwhitney_de

### ISSUE THREAD

**Issue by drosofff** [ARTbio/tools-artbio#403]
- [x] sort differential list by p-adj !
edit [this](https://github.com/ARTbio/tools-artbio/blob/b839b440f0760ff9cd75969d418432702947a669/tools/gsc_mannwhitney_de/MannWhitney_DE.R#L138)

- [x] the column "significant" is of no use, at minimum replace its level by up, down and ns
- [x] the tool claims that it takes as input a metadata file with "at least" two columns (cells and factor). But this is not true: the metadata must currently have **exactly** two columns, which is two bad (the user should avoid pre-using a cut step !)

**Comment by bellenger-l** [comment]
@drosofff Initially the metadata had several column and there were an additional parameter to find the correct column score. After discussion, we agreed to limited the metadata file to two columns. But I can easily go back to what it was.

**Comment by drosofff** [comment]
There is maybe some improvements already implemented since I raised this issue. Look I do not remember. as far as the column number is concerned, I am happy with a 2-columns file that does what it says it does ! Simplicity is gold

**Comment by drosofff** [comment]
addressed by #422

**Comment by drosofff** [comment]
Thanks @bellenger-l I can close the issue then
