### ISSUE TITLE
Improve gsc_signature_score

### ISSUE THREAD

**Issue by drosofff** [ARTbio/tools-artbio#404]
- We want more info on the signature with this tool !
return a report with covariance matrix of the signature genes, correlation matrix of the signature genes

- The plot of rang-signature is not so informative. Much better to directly plot violins in function of factor (less that mean, more than mean), or other interesting factors.

- Restructure le code so that the signature computing is a function that can be changed

**Comment by bellenger-l** [comment]
@drosofff improvements were done ?

**Comment by drosofff** [comment]
The two first points are done.
Not the last one. I will close this issue and reopen one that focuses on it
