### ISSUE TITLE
Fetch Fasta from NCBI doesn't work

### ISSUE THREAD

**Issue by ccedmendoza** [ARTbio/tools-artbio#425]
**Describe the bug**

When running the tool, no matter the entrez query, it errors. When running the tool while Setting the option "Get only the number of sequences" as "Yes" the dataset is green but the number of sequences is not there.

In my opinion, for some reason the tool can't reach the server.

**To Reproduce**
1. Go to 'Retrieve Fasta from NCBI'
2. Click on 'Query to NCBI in entrez format'
3. Write 'phix174[title]'
4. Run the tool

**Expected behavior**

Download 154 sequences

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Frirefox

**Comment by drosofff** [comment]
Tool execution generated the following messages:
```
head: cannot open 'uid_outfile' for reading: No such file or directory
```

**Comment by drosofff** [comment]
eutils service seems down:

https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ecitmatch.cgi?db=pubmed&retmode=xml&bdata=proc+natl+acad+sci+u+s+a|1991|88|3248|mann+bj|Art1|%0Dscience|1987|235|182|palmenberg+ac|Art2|

return currently:
```
Unable to route request!

service name: /http/service/ratecontrol
dtab:

base dtab:

override dtab:
```

**Comment by ccedmendoza** [comment]
Perfect, the eutils are up and running again 👍
