### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by LliliansCalvo** [ARTbio/tools-artbio#461]
I am trying to run the script in a bam file and I keep getting this error? Any idea how to sort this?

samtools index sorted_g.mapped_TEs_new_f.bam && overlapping_reads.py --input sorted_g.mapped_TEs_new_f.bam --minquery 25 --maxquery 35 --mintarget 25 --maxtarget 35 --overlap 10 --output pairable_sequences.sorted_g.mapped_TEs_new_f.fasta

File "/Users/user/bin/overlapping_reads.py", line 168, in <module>
    args.mintarget, args.maxtarget, args.overlap)
  File "/Users/user/bin/overlapping_reads.py", line 48, in __init__
    overlap=self.overlap)
  File "/Users/user/bin/overlapping_reads.py", line 79, in query_positions
    for genomicKey in self.alignement_dic.keys():
RuntimeError: dictionary changed size during iteration

Thanks a lot!

**Comment by drosofff** [comment]
@LliliansCalvo Sorrry I have no idea what you are talking about.
Please, conform to the bug form template and if possible give access to your sorted_g.mapped_TEs_new_f.bam file (or the 1000 first alignments plus the header), this is most probably where the problem is lying

**Comment by LliliansCalvo** [comment]
Thanks, it was some sort of incompatibility error between python versions in my computer. I just added this to the script (#!/Users/user/.pyenv/shims/Python) and then run it like this python2.7 overlapping_reads.py and that solved it.

**Comment by drosofff** [comment]
Ok. the best is to create a conda environment with the requirements as indicated in the xml wrapper, and then to run the tool scripts within this env. This is all what Galaxy is doing ;-)
