### ISSUE TITLE
Size distribution and Readmaps is ugly with only one sample

### ISSUE THREAD

**Issue by drosofff** [ARTbio/tools-artbio#5]
see https://github.com/ARTbio/tools-artbio/tree/master/tools/msp_sr_readmap_and_size_histograms
The tool is programmed to return a figure with several columns of read map & read distributions, corresponding to several sample (One row by sequence/items in the bowte index).
When there is only one sample, the width of the figures reduces to the width of one column, which is a bit frustrating since this configuration generally occurs when you just want to describe this sample and therefore you would favor larger graphs.
![capture d ecran 2015-09-12 a 14 58 47](https://cloud.githubusercontent.com/assets/11705625/9831611/e30af30c-595e-11e5-9242-457a0f715e17.png)

**Comment by mvdbeek** [comment]
I can work on this, as I already have a ggplot version of this code for my paper.
Which has the advantage of being easier to modify after the actual plotting (e.g. with plot.ly), and should at some point be natively supported in python.
But low priority, if that's OK with you.

**Comment by drosofff** [comment]
yes low priority for sure


Christophe Antoniewski

Drosophila Genetics and Epigenetics
Institut de Biologie Paris Seine
<http://www.ibps.upmc.fr/fr/Recherche/umr-biologie-developpement/genetique-et-epigenetique-de-la-drosophile>
9, Quai St Bernard, Boîte courrier 24
75252 Paris Cedex 05

Tel +33 1 44 27 34 39
Fax +33 1 44 27 34 45
Mobile +33 6 68 60 51 50
christophe.antoniewski@upmc.fr

http://drosophile.org

2015-09-12 17:57 GMT+02:00 Marius van den Beek <notifications@github.com>:

**Comment by drosofff** [comment]
fixed in https://github.com/ARTbio/tools-artbio/pull/40
