### ISSUE TITLE
Receiving "python: command not found" error on execution

### ISSUE THREAD

**Issue by quacksawbones** [ARTbio/tools-artbio#508]
We're trying to execute Oases on Galaxy 20.09 using Singularity 3.7.1, and we recieve the following error message:

`/srv/galaxy/jobs/000/9/tool_script.sh: line 22: python: command not found`

We have created a brand new CentOS 7 virtual machine with VirtualBox 6, loaded Galaxy via Ansible (broadly following the instructions here (https://training.galaxyproject.org/training-material/topics/admin/tutorials/singularity/tutorial.html), customising to work with CentOS 7 where needed). I am then installing Oases (and dependencies) and trying to execute using some loaded fasta data (short reads coverted from fastq sequencing data). It is building a mulled Singularity container for execution.

 - OS: CentOS 7
 - Browser: Firefox (via Galaxy and Nginx)
 - Version: Galaxy: 20.09, oasesoptimiserv: 1.2.2

We don't seem to have this issue with other tools loaded into the galaxy system (for example, minimap2). Happy to provide any other information you need.

Thanks

**Comment by drosofff** [comment]
Hi @quacksawbones ,
Providing `/srv/galaxy/jobs/000/9/tool_script.sh` content would be a good start. But before I am wondering why you are raising this issue in the artbio/tools-artbio repo. Is there a reason to suspect that the tool [oases](https://toolshed.g2.bx.psu.edu/view/artbio/oases/f7dd852c8f4c) is implied in the issue ?

**Comment by quacksawbones** [comment]
Thanks for the swift reply. Sorry, I completely forgot to attach it (this script is generated by Galaxy when the tool is executed in the user interface):

`#!/bin/bash

# The following block can be used by the job system
# to ensure this script is runnable before actually attempting
# to run it.
if [ -n "$ABC_TEST_JOB_SCRIPT_INTEGRITY_XYZ" ]; then
    exit 42
fi

# Check if container was created by installing conda packages,
# and if so, source scripts to populate environment variables
# that would be set by activating the conda environment.
if [ -d /usr/local/etc/conda/activate.d ]; then
  export CONDA_PREFIX=/usr/local
  for f in /usr/local/etc/conda/activate.d/*.sh; do
    case "$f" in
      "/usr/local/etc/conda/activate.d/activate-"*) :;;
      *) . "$f" ;;
    esac;
  done
fi
python "<path to galaxy>/toolshed.g2.bx.psu.edu/repos/artbio/oases/f7dd852c8f4c/oases"/oases_optimiser.py  "11" "25" "/data/000/dataset_7.dat"`

I suspect there are some dependencies within this tool's configuration that are not correctly handled when this is installed by Galaxy. The reason I am brining it up here is because I have not encountered this problem it with any other tool I have installed on my Galaxy instances so far.

Thankyou.

**Comment by drosofff** [comment]
Thanks @quacksawbones I may be wrong but the initial error seems to be that the python command (' python: command not found' ) is not found in the path. That is, before searching to execute specifically the oases_optimiser.py script. So, if there is a problem with the conda environment, I would say that the first missing dependency is... python itself. Which makes no sense to me :-(.
Searching in the direction of the singularity container is another option.

In the meantime if I will repeat the test of the tool using planemo and keep you posted

**Comment by drosofff** [comment]
FYI:

```
done ; python "/home/chris/.planemo/planemo_tmp_h2_q83uh"/oases_optimiser.py  "15" "35" "/tmp/tmpv7s5wfrb/files/b/e/c/dataset_bec83658-0ce2-412c-8259-5a7a3424ce67.dat" "/tmp/tmpv7s5wfrb/files/6/1/b/dataset_61b2db32-82b5-4849-83a9-683708dabe7e.dat"]
ok

----------------------------------------------------------------------
XML: /tmp/tmpv7s5wfrb/xunit.xml
----------------------------------------------------------------------
Ran 1 test in 28.248s

OK
2021-03-04 14:21:18,569 INFO  [test_driver] Shutting down
2021-03-04 14:21:18,569 INFO  [test_driver] Shutting down embedded galaxy web server
2021-03-04 14:21:18,571 INFO  [test_driver] Embedded web server galaxy stopped
2021-03-04 14:21:18,572 INFO  [test_driver] Stopping application galaxy
2021-03-04 14:21:19,531 INFO  [galaxy.queue_worker] Sending reconfigure_watcher control task.
2021-03-04 14:21:19,562 INFO  [galaxy.jobs.handler] sending stop signal to worker thread
2021-03-04 14:21:19,562 INFO  [galaxy.jobs.handler] job handler queue stopped
2021-03-04 14:21:19,562 INFO  [galaxy.jobs.runners] LocalRunner: Sending stop signal to 4 job worker threads
2021-03-04 14:21:19,562 INFO  [galaxy.jobs.runners] Waiting up to 5 seconds for job worker threads to shutdown...
2021-03-04 14:21:19,563 INFO  [galaxy.jobs.runners] All job worker threads shutdown cleanly
2021-03-04 14:21:19,563 INFO  [galaxy.jobs.runners] TaskRunner: Sending stop signal to 2 job worker threads
2021-03-04 14:21:19,564 INFO  [galaxy.jobs.runners] Waiting up to 5 seconds for job worker threads to shutdown...
2021-03-04 14:21:19,564 INFO  [galaxy.jobs.runners] All job worker threads shutdown cleanly
2021-03-04 14:21:19,564 INFO  [galaxy.jobs.handler] sending stop signal to worker thread
2021-03-04 14:21:19,565 INFO  [galaxy.jobs.handler] job handler stop queue stopped
2021-03-04 14:21:19,565 INFO  [test_driver] Application galaxy stopped.
Testing complete. HTML report is in "/home/chris/tools-artbio/tools/oases/tool_test_output.html".
All 1 test(s) executed passed.
oasesoptimiserv[0]: passed
```

**Comment by quacksawbones** [comment]
So, what I'm trying to do is load the tools necessary to run the Metavisitor pipelines as described in the workflows here (https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0168397). Unfortunately, when I load this repository using the Galaxy Toolshed (https://toolshed.g2.bx.psu.edu/repository?repository_id=b464e6cbf956157e&changeset_revision=f7dd852c8f4c), something is not deploying or installing correctly.

Is there any way I can see how you've configured your Galaxy instance so I can try to determine what is misconfigured on mine? (Happy to continue this conversation via e-mail if needed).

**Comment by quacksawbones** [comment]
After bringing the problem up with the Galaxy community (https://gitter.im/galaxyproject/admins?at=6043642ed74bbe49e0d83786), their suggestion is that the tool descriptor does not include a python dependency, which is why when I download, install and try to execute the tool within Galaxy, I am receiving the Python error.

Can the Galaxy configuration of this tool be modified to include the necessary Python dependency?

**Comment by drosofff** [comment]
Hi @quacksawbones
As suggested, I have add python to the dependencies in PR #509

Let's see whether is goes better with that

**Comment by quacksawbones** [comment]
Hi @drosofff,

Thankyou, I really appreciate it. I will have another go and let you know how it goes.

Thanks again

**Comment by quacksawbones** [comment]
Hi @drosofff,

I have just installed the latest version of oasesoptimiserv (1.3.0), and the addition of the python dependency worked. It is now executing both locally and via our cluster.

Thanks again for your help

**Comment by drosofff** [comment]
Good to know @quacksawbones  ! I though a python environment was always available by default, but apparently it is not the case in a singularity container. Learned something today ! Thanks

**Comment by drosofff** [comment]
> I think that's how it all works... :)

Yes indeed. I have been misled by the `base` conda environment which does contain a python. 
But, actually, `conda create -n null` builds an `null` environment  that contains... nothing

```
(null) chris@plastisipi:~/tools-artbio/tools/oases$ conda list
# packages in environment at /home/chris/conda/envs/null:
#
# Name                    Version                   Build  Channel
``` 
Stunning isn't it ? I told you, I have learned something ! Thank U

**Comment by quacksawbones** [comment]
Hi @drosofff, unfortunately I am now receiving the same "Python not found" error when trying to execute the "BlastParser_and_hits.py" tool within Galaxy. I believe it is the same cause as with "oases_optimiser.py" above (the Python dependency has not been defined within the "BlastParser_and_hits.xml" tool definition) and should be resolved by putting the necessary Python version into the XML file.

Would you like me to reopen this issue or create a new issue?

**Comment by quacksawbones** [comment]
Brilliant. I can confirm that has fixed it and it now executes without an issue 👍 

Thanks @drosofff
