### ISSUE TITLE
cherry_pick_fasta - "Equals" or "Exact match" functionality for Match Criteria

### ISSUE THREAD

**Issue by quacksawbones** [ARTbio/tools-artbio#531]
Currently, when I have a list of sequences that all contain an identical subsequence:

- ABC_QC1
- ABC_QC2
- ...
- ABC_QC10
- ABC_QC11

When using "contains" as the match criteria for the query "ABC_QC1", the tool finds matches to ABC_QC1, ABC_QC10, ABC_QC11 and anything else that includes "ABC_QC1" in the header in some way. This doesn't work when trying to extract just the ABC_QC1 sequence, or any other scenario when the subsequences match the search criteria and an exact match is required.

Having an additional option to retrieve an "Exact Match" for the query would mean that I can extract a single sequence based on a specific search term without having to rename/rebuild my entire FASTA file.

Including this in the Galaxy implementation is also needed if this tool gets updated.

Thanks,

Darren Cullerne

**Comment by drosofff** [comment]
OK @quacksawbones I am on it. It should not be to long to fix (see PR #533)

**Comment by drosofff** [comment]
Done @quacksawbones (#533)

What do you mean exactly by 

> Including this in the Galaxy implementation is also needed if this tool gets updated.

?

**Comment by quacksawbones** [comment]
Hi @drosofff, I was not sure if updating the tool would also push the update to Galaxy. But it has :)

I've installed 3.0.1 and can confirm the "exactly" functionality behaves as expected.

Thanks again,

DC
