### ISSUE TITLE
get_tool_yml_from_gi.py errors on empty sections / incomplete output?

### ISSUE THREAD

**Issue by mvdbeek** [ARTbio/tools-artbio#55]
report by @methylome [here](https://github.com/galaxyproject/galaxy/issues/1563#issuecomment-182109409)

**Comment by methylome** [comment]
How can we check the output of the script is complete?

**Comment by mvdbeek** [comment]
Your approach was not too bad.
If you count the number of installed repositories in the admin panel, and you subtract packages and suites you should get to the number of revisions listed in the output file.
If you don't mind sharing the output file and either the shed_tool_conf.xml or the html from the admin panel I can do this for you.

**Comment by methylome** [comment]
I haven't considered packages. The number in the output file seems correct. I've attached the file.
[shed_tool_conf.xml.gz](https://github.com/ARTbio/tools-artbio/files/124612/shed_tool_conf.xml.gz)

**Comment by mvdbeek** [comment]
Awesome. If you want me to double-check I also need the output file from get_tool_yml_from_gi.py .

**Comment by methylome** [comment]
[tool_list.yml.gz](https://github.com/ARTbio/tools-artbio/files/124621/tool_list.yml.gz)

Please double check it.

**Comment by methylome** [comment]
FYI, I've attached the output of printing sections.
[section.json.gz](https://github.com/ARTbio/tools-artbio/files/124625/section.json.gz)

**Comment by mvdbeek** [comment]
Hmm, 5 revisions are missing in the output file:
```
grep installed_changeset_revision shed_tool_conf.xml | sed -e 's/^[[:space:]]*//'|sed -e 's/<[^>]*>//g'|uniq | xargs -I {} sh -c "grep -c {} tool_list.yml; echo {}"
```
These are

```
e23b0cdeeba6
94d5786febc4
09a7281d24c5
91cce7c1436d
0ef7736004bb
```

That's bowtie2, samtool_filter2, bwa_mem, yac_clipper and flexbar.
Very strange ...

**Comment by mvdbeek** [comment]
ahh, I have an idea.
Can you check if `e23b0cdeeba6` appears anywhere in your admin section?
It could be a revision that has been uninstalled, but that is still present in shed_tool_conf.xml.
Because I also don't see these revisions in the section.json that you attached.
If that is the case, the list should be complete.

**Comment by methylome** [comment]
No it doesn't. It seems you got the problem.

**Comment by methylome** [comment]
Yes, you are right. All of them don't appear.

Thanks so much.
Justin.

**Comment by mvdbeek** [comment]
No problem, you're welcome!

**Comment by methylome** [comment]
Hi @mvdbeek,

I cloned a galaxy server and tried to install the yaml file from another server using install_tool_shed_tools.py. Shouldn't this work? The following shows galaxy logs:

158.93.190.101 - - [29/Feb/2016:21:07:26 -0400] "GET /galaxy/api/tool_shed_repositories?key=90a19ccd59e393b187cd70fc949888ca HTTP/1.1" 200 - "-" "python-requests/2.9.1"
warning: toolshed.g2.bx.psu.edu certificate with fingerprint 54:1e:bc:3d:37:34:25:8a:77:35:ce:d9:2d:48:88:65:27:d0:0a:76 not verified (check hostfingerprints or web.cacerts config setting)
tool_shed.galaxy_install.install_manager ERROR 2016-02-29 21:07:30,783 No content returned from tool shed repository version request to https://toolshed.g2.bx.psu.edu/repository/get_tool_versions?owner=iuc&changeset_revision=ded58f1da91c&name=package_abyss_1_9_0
tool_shed.galaxy_install.tool_dependencies.recipe.tag_handler ERROR 2016-02-29 21:07:32,598 Error installing tool dependency for required repository: This tool dependency's required tool dependency boost version 1.57 has status Error.
tool_shed.galaxy_install.tool_dependencies.recipe.tag_handler ERROR 2016-02-29 21:07:33,265 Error installing tool dependency for required repository: This tool dependency's required tool dependency sqlite version 3.8.3 has status Error.
...

The log of the scripts:
(1/148) Installing tool analyze_covariates from devteam to section "NGS: GATK" at revision 738bc749f9a3 (TRT: 0:00:00.897487)
        Tool analyze_covariates installed successfully (in 0:01:58.468680) at revision 738bc749f9a3
(2/148) Installing tool bam_to_sam from devteam to section "NGS: SAM/BAM manipulation" at revision c09a20532957 (TRT: 0:01:59.609308)
        Tool bam_to_sam installed successfully (in 0:00:10.265186) at revision c09a20532957
...

Are these really errors?
Thanks,
Justin.

**Comment by mvdbeek** [comment]
Hard to say ...
```
tool_shed.galaxy_install.install_manager ERROR 2016-02-29 21:07:30,783 No content returned from tool shed repository version request to https://toolshed.g2.bx.psu.edu/repository/get_tool_versions?owner=iuc&changeset_revision=ded58f1da91c&name=package_abyss_1_9_0
```

This is not necessarily an error, it can be an unavailable changeset revision.
```
tool_shed.galaxy_install.tool_dependencies.recipe.tag_handler ERROR 2016-02-29 21:07:32,598 Error installing tool dependency for required repository: This tool dependency's required tool dependency boost version 1.57 has status Error.
tool_shed.galaxy_install.tool_dependencies.recipe.tag_handler ERROR 2016-02-29 21:07:33,265 Error installing tool dependency for required repository: This tool dependency's required tool dependency sqlite version 3.8.3 has status Error.
```

These are probably errors. I'd recommend looking at the individual tools in the admin panel.
One thing pops to mind: Did you set a tool_dependency_dir in galaxy.ini ?

**Comment by methylome** [comment]
Yes, it is.
tool_dependency_dir = software

Installation of many tools has been failed.
For package_cufflinks_2_2_1, galaxy shows the following log but doesn't list files in the directory.
The installation directory for this tool dependency had contents but the database had no record. The installation log may show this tool dependency to be correctly installed, but due to the missing database record it is now being set to Error.

ll ./software/cufflinks/2.2.1/devteam/package_cufflinks_2_2_1/899067a260d1 
total 12
drwxr-x--- 2 galaxy galaxy 4096 Sep  6 00:57 bin
-rwxr-x--x 1 galaxy galaxy  110 Sep  6 00:57 env.sh
-rw-r----- 1 galaxy galaxy  132 Sep  6 00:57 INSTALLATION.log

I confirmed many tools are the same. Do you have any idea?
Thanks,
Justin.

**Comment by mvdbeek** [comment]
Well, the tool_dependency_dir needs to be clean before starting.
```
The installation directory for this tool dependency had contents but the database had no 
```

**Comment by methylome** [comment]
The location of shed_tools is different from what I expect. The new copy of shed_tool_conf.xml.sample:
<?xml version="1.0"?>
<toolbox tool_path="../shed_tools">
</toolbox>

With this setting, the shed_tools was created on the parent of the galaxy directory. Is this correct?

**Comment by mvdbeek** [comment]
Yes, if you don't set an absolute path, relative paths are resolved from the galaxy directory.

**Comment by methylome** [comment]
After cleaning the shed_tools and tool_dependency_dir, the installation is working.

Thanks a lot,
Justin.

**Comment by mvdbeek** [comment]
awesome, glad it works.

**Comment by methylome** [comment]
I have another problem. After successful installation, galaxy doesn't list the installed files on Browse tool dependency installation directory, but ls does. What's wrong?

**Comment by mvdbeek** [comment]
That's really a galaxy question, it would receive more visibility on the mailing list or in galaxy's github.
I'm not exactly sure, are you using a relative path that includes ``../`` ?
It might be for security reasons or it might be a bug ... try with an absolute path.
