### ISSUE TITLE
Unused tool parameters

### ISSUE THREAD

**Issue by bernt-matthias** [ARTbio/tools-artbio#576]
**Describe the bug**

With https://github.com/galaxyproject/galaxy/pull/12724 planemo lint may error on input parameters that are not used:

- [x] tools/gatk4/Mutect2.xml has some .. tool should be deprecated (is in IUC)
- [x] tools/justgzip/gzip.xml
  - datatype
- [x] tools/manta/manta.xml
  - additional_param
- [x] tools/pathifier/pathifier.xml
  - rdata
- [x] tools/small_rna_clusters/small_rna_clusters.xml
  - first_plot

**Comment by drosofff** [comment]
@bernt-matthias wrote:

> tools/justgzip/gzip.xml
> datatype

the datatype parameter is used in the <change_format> tag:
```
   <change_format>
       <when input="datatype" value="sanger" format="fastqsanger.gz" />
       <when input="datatype" value="illumina" format="fastqillumina.gz" />
   </change_format>
```

**Comment by bernt-matthias** [comment]
> the datatype parameter is used in the <change_format> tag:

True, still this https://github.com/ARTbio/tools-artbio/pull/580 might be better?
