### ISSUE TITLE
The sra_tools tool fails running on lbcd41.snv.jussieu.fr

### ISSUE THREAD

**Issue by drosofff** [ARTbio/tools-artbio#6]
https://github.com/ARTbio/tools-artbio/tree/master/tools/sra-tools

Extract reads in FASTQ/A format from NCBI SRA. (Galaxy Tool Version 1.1.11) tool, with form filled with
- SRR1914952 (accession field)
- no (split spot by read pairs)
- other field empty or unchanged
fails and return the galaxy error:

Fatal error: Exit code 127 (Could not locate fastq-dump binary)
/home/galaxy/galaxy-dist/database/job_working_directory/088/88795/galaxy_88795.sh: line 39: vdb-config: command not found
/home/galaxy/galaxy-dist/database/job_working_directory/088/88795/galaxy_88795.sh: line 39: vdb-config: command not found
/home/galaxy/galaxy-dist/database/job_working_directory/088/88795/galaxy_88795.sh: line 39: prefetch: command not found
/home/galaxy/galaxy-dist/database/job_working_directory/088/88795/galaxy_88795.sh: line 39: vdb-config: command not found
/home/galaxy/galaxy-dist/database/job_working_directory/088/88795/galaxy_88795.sh: line 39: fastq-dump: command not found

seems like a problem in the tool_dependencies.xml file and PATH definition ?

By the way, is it possible to quickly attach an issue to a file (or a file to an issue) in GitHub ?

**Comment by mvdbeek** [comment]
Interesting. This is linked to https://github.com/galaxyproject/galaxy/pull/707 .
I think that constructing the PATH is broken now for very specific circumstances,
as is installing/uninstalling packages. This should stay open until the upstream galaxy issue is resolved.
In fact the tool works fine when installed in a fresh galaxy instance.

**Comment by drosofff** [comment]
OK. Just to make it sure: is galaxy in lbcd41 at the latest revision of the code ?

**Comment by mvdbeek** [comment]
Of the tool? yes. For the PR, initially the PR was applied.
I'll check if it works without the PR.

**Comment by mvdbeek** [comment]
Without the PR it is exactly the same problem.

**Comment by mvdbeek** [comment]
@drosofff Can you test it now (both mississippi and plastisipi got the tools)? 
Should be fixed with PR #14 and PR #17 
If it works for you, can you close the issue?

**Comment by drosofff** [comment]
Yes ! it worked on both instances with SRR016820.
I still found the form of the tool a bit scary if you just want to get data and don't know the details of sra toolkit functionalities. Maybe a more detailed help section, or conditional fields to fill in ? In any case the issue is fixed, I close it, thanks !
