### ISSUE TITLE
Overlapping_reads.py for Python 3 Output Bug

### ISSUE THREAD

**Issue by Beazan** [ARTbio/tools-artbio#612]
**Describe the bug**
When trying to run the updated version of the overlapping_reads.py using python 3.10.8 the slurm job output file gets inputs from the data processed to produced the output fasta file. This generates slurm output files of a few Gbs that are inconvenient when trying to find other information from the file such as mapping stats from bowtie. The previous scripts, for python 2.7, did not have this feature. I am not sure if it's intentional or a bug on the updated code. The image below is what myoutput-####.txt looks like after running the updated version and it's 2.5Gbs in size. There are other bowtie alignment stats in the file that are hard to locate due to the thousand of lines of reads. 

<img width="1741" alt="Screen Shot 2023-02-24 at 3 29 18 PM" src="https://user-images.githubusercontent.com/125386983/221296809-4afd6114-9116-460d-80d3-905bef45acaf.png">

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by drosofff** [comment]
Yeah @Beazan , that was just some print statements to the standard output for debugging purposes. These statements were removed in the in the v3.4.2 wappers !
