### ISSUE TITLE
galaxy wrapper fails with an error about an unknown svtyper option

### ISSUE THREAD

**Issue by hepcat72** [ARTbio/tools-artbio#614]
**Describe the bug**

When I run the lumpy_smoove galaxy wrapper, I get the error:

`svtyper: error: unrecognized arguments: --max_ci_dist 0`

In the job's stderr output.

**To Reproduce**
1. I ran it on a single bam file as a part of a workflow with the following settings:
<img width="249" alt="smoove" src="https://user-images.githubusercontent.com/2300532/225767150-1f9986b8-9c86-45ab-abc9-defeada3e181.png">

**Expected behavior**

No error.

**Screenshots**

<img width="1060" alt="smooveerr" src="https://user-images.githubusercontent.com/2300532/225767352-c87781bc-d2d0-4262-b69d-45267c52b10f.png">

**Desktop (please complete the following information):**
 - OS: macOS X
 - Browser safari
 - Version Galaxy Version 0.2.5+galaxy8

**Additional context**

The galaxy toolshed linked to this repo, so I'm only assuming that you developed the galaxy wrapper named `lumpy_smoove`.

This is apparently a known issue with a [known solution](https://github.com/brentp/smoove/issues/13#issuecomment-637873605).

Just need to update the `svtyper` dependency.

**Comment by drosofff** [comment]
Hi @hepcat72 

Sorry for the delay, I was stuck with other things.
Yes I will look at this issue and probably come back to you to test its resolution.
Cheers

**Comment by drosofff** [comment]
@hepcat72 can you reproduce the error on our [Mississippi Galaxy server](https://mississippi.sorbonne-universite.fr) ?

**Comment by hepcat72** [comment]
I'm not sure this is something that is an issue with the galaxy wrapper. It's in the smoove Vonda dependencies. I can reproduce it on the command line by creating a condo environment for smoove and running it with the --genotype option. The workaround is to pip-install a newer version of svtyper, which anyone can do on their galaxy install, so unless I know if that was done or not on that galaxy install, I'm not sure a test would be informative.

I believe I created an issue in the smoove repo for this. At least, I hope I did.

**Comment by drosofff** [comment]
@hepcat72 yes I saw https://github.com/bioconda/bioconda-recipes/issues/39967.
From what I can see, there is a problem of incompatibility to build a conda environment with smoove=0.2.8 and svtyper > 0.1.4. Usual business I would say.

In any case the current galaxy wrapper is working with smoove=0.2.5. I will try another turnaround, ie building first a svtyper=0.7.1 environment and installing smoove=0.2.8 on top of it.

I don't know yet if this is possible with the galaxy_wrapper, but in a pure conda env, it is working:

```
(svtyper) conda list
# packages in environment at /home/chris/conda/envs/svtyper:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
bcftools                  1.8                  h4da6232_3    bioconda
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
certifi                   2019.11.28       py27h8c360ce_1    conda-forge
curl                      7.71.1               he644dc0_0    conda-forge
cytoolz                   0.10.1           py27h516909a_0    conda-forge
duphold                   0.2.1                h516909a_1    bioconda
gawk                      5.1.0                h516909a_0    conda-forge
gsort                     0.1.4                h9ee0642_1    bioconda
htslib                    1.9                  h4da6232_3    bioconda
krb5                      1.17.1               hfafb76e_1    conda-forge
ld_impl_linux-64          2.34                 h53a641e_5    conda-forge
ldc                       1.20.0               h9a1ace1_1    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libcurl                   7.71.1               hcdd3856_0    conda-forge
libdeflate                1.5                  h516909a_0    conda-forge
libedit                   3.1.20191231         h46ee950_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.5.0                hdf63c60_6    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libopenblas               0.3.10               h5ec1e0e_0    conda-forge
libssh2                   1.9.0                hab1572f_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
llvm-openmp               10.0.0               hc9558a2_0    conda-forge
lumpy-sv                  0.3.0                ha52163a_3    bioconda
mosdepth                  0.3.3                hdfd78af_1    bioconda
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.16.5           py27h95a1406_0    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
pandas                    0.24.2           py27hb3f55d8_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pip                       20.1.1             pyh9f0ad1d_0    conda-forge
pysam                     0.15.4           py27hbcae180_0    bioconda
python                    2.7.15          h5a48372_1011_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                2.7                    1_cp27mu    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
sambamba                  0.7.1                h148d290_2    bioconda
samblaster                0.1.26               hc9558a2_0    bioconda
samtools                  1.9                 h10a08f8_12    bioconda
scipy                     1.2.1            py27h921218d_2    conda-forge
setuptools                44.0.0                   py27_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smoove                    0.2.8                h9ee0642_1    bioconda
sqlite                    3.32.3               hcee41ef_0    conda-forge
statsmodels               0.10.2           py27hc1659b7_0    conda-forge
svtools                   0.3.2            py27h24bf2e0_2    bioconda
svtyper                   0.7.1                      py_0    bioconda
tk                        8.6.10               hed695b0_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
util-linux                2.35             py27hfbfebf4_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```

**Comment by hepcat72** [comment]
If I run the automated galaxy install of the galaxy wrapper using the galaxy admin panel, perhaps the older version may work - I only tried the latest, but the default selected version gets the error above.

I uninstalled it so our users wouldn't hit the error. I know that there exist ways to build it in a manual fashion so it works, but it's that automated install that encounters the problem and that's what I was creating the issue about here.

**Comment by drosofff** [comment]
Mmm mmm, I am missing something because the automated tests of the current, latest version of the galaxy wrapper are working. In a clean, automated galaxy install, you should target smoove 0.2.5 and it should work.

**Comment by hepcat72** [comment]
I believe that, because I get no error on the install, but I assume there is no test for my use-case (inclusion of the `--genotype` flag).  I could be wrong and there's some other aspect that is the issue.  But this is the command line call that reveals the error:
```
set -o | grep -q pipefail && set -o pipefail;  ln -s '/galaxy/files/000/693/dataset_693782.dat' reference.fa && samtools faidx 'reference.fa' 2>&1 || echo "Error running samtools faidx for lumpy_smoove" >&2 &&  ln -s /galaxy/files/000/693/dataset_693835.dat single.bam && ln -f -s /galaxy/files/_metadata_files/056/metadata_56491.dat single.bam.bai &&  smoove call --name output --fasta reference.fa --processes ${GALAXY_SLOTS:-4} --genotype --removepr *.bam && gunzip -c output-smoove.genotyped.vcf.gz > /galaxy/files/000/693/dataset_693840.dat
```
I do not get an error on the command line if `--genotype` is not supplied.  Since it's uninstalled on our galaxy, I can't see the options and looking at the screenshot of the options I provided above, I don't see a GUI option that maps directly to `--genotype`, but maybe I failed to capture it...

But it was telling to me that when I simply did a `conda env create --name smoove smoove` on a different machine, I got the exact same error that I got on galaxy.

**Comment by hepcat72** [comment]
I assumed galaxy was essentially doing the same conda environmental setup.

**Comment by drosofff** [comment]
This is all a bit confusing for me but we will soon know if the new version of svtyper solves your problem:

The test of the new version of the wrapper is in progress on this Github repo and I should be able to push it into the toolshed in about 15 min

**Comment by drosofff** [comment]
Yeap @hepcat72 Tell me whether the new wrapper is fixing your issue

https://github.com/ARTbio/tools-artbio/actions/runs/4620174699/jobs/8170459257#step:6:218
