### ISSUE TITLE
multiple SRR inputs would be great in tools-artbio/tools/sra-tools/fastq_dump.xml

### ISSUE THREAD

**Issue by drosofff** [ARTbio/tools-artbio#62]
Especially for metavisitor

**Comment by mvdbeek** [comment]
Yes, all of the SRA tools should support this.
I guess the best way would be to feed a tabular file with all the SRR codes that you want.
We can use the get_sra_info tool to make this file from SRP accessions.

**Comment by mvdbeek** [comment]
OK, you can do this now in the latest version of the sratools
![screen shot 2016-10-08 at 7 16 38 pm](https://cloud.githubusercontent.com/assets/6804901/19214769/d680aa48-8d8b-11e6-8d2a-99db0c294c30.png)

**Comment by drosofff** [comment]
Nice 👍 
I let open the issue to update the metavisitor doc. uploading the sra dataset was a pain in the ass. It makes it easy now

**Comment by drosofff** [comment]
Check this tool. It's not clear that it is still working

**Comment by ccedmendoza** [comment]
The iuc sra tool works
