### ISSUE TITLE
Make a simple tool SAM to FASTQ to speed up metavisitor workflows

### ISSUE THREAD

**Issue by drosofff** [ARTbio/tools-artbio#66]
This would allow to use bowtie2 for a SAM output, skipping any samtools sorting

**Comment by mvdbeek** [comment]
yes, probably the best option.
http://www.cureffi.org/2013/07/04/how-to-convert-sam-to-fastq-with-unix-command-line-tools/

**Comment by drosofff** [comment]
The bowtie2 wrapper has been fixed to output a SAM file and Unmatched reads. Did not check for bowtie, but in any case bowtie2 can be used instead of bowtie right ?

**Comment by mvdbeek** [comment]
Yes. Does bowtie1 even support outputting aligned reads?
