### ISSUE TITLE
manta tool does not output any file by default

### ISSUE THREAD

**Issue by bgruening** [ARTbio/tools-artbio#660]
The outputs are all booleans and it is possible to submit a job with NO output. Even worse its the default setting :)

**Comment by drosofff** [comment]
Yeah... You probably did not notice it @bgruening but I am systematically refreshing the tools. Last weeks I was on Lumpy-Smoove and the next one on the list is... Manta !

I fear the worst !

Shall I jump directly to `mapping_quality_stats` ? I need to sleep...  sometimes ;-)

**Comment by drosofff** [comment]
@bgruening I have reviewed the manta wrapper.

To me this looks like a monstrous wrapper of wrapper of wrapper. Beside the issue you mentioned last week, it's a miracle that 4/5 tests pass...

We can clarify and fix, for sure.
However,
- The support to the [original tool ](https://github.com/Illumina/manta) seems dropped
- A quick pubmed survey does not give the impression that it is the "blast" of the SV detection (far from)
- My entourage, which is quite varied, does not use Manta
- The conda community does not push the manta package like crazy
- Myself I rather focus on lumpy/smoove or radically different approaches based on B-allele frequencies

Although I can admit that none of these points are really strong and the Manta wrapper has been installed 165 times (not by me !), I have mixed feelings.

Do you think it's worth maintaining the Galaxy Manta wrapper ?

Tell me what you think (other opinions are also welcome), I will definitely take it into account.

**Comment by bgruening** [comment]
I agree we should probably deprecate it. But I'm unsure we we should fix this last problem. It seems to be relatively easy to rearrange the outputs in the Galaxy wrapper, no?

I will hide the tool on the EU server, do you agree?

**Comment by drosofff** [comment]
> It seems to be relatively easy to rearrange the outputs in the Galaxy wrapper, no?

OK, I'll do it

> I will hide the tool on the EU server, do you agree?

No problem with that

**Comment by drosofff** [comment]
See PR  #669, @bgruening
