### ISSUE TITLE
Fetch sequences from NCBI tool

### ISSUE THREAD

**Issue by drosofff** [ARTbio/tools-artbio#76]
The tool available here https://github.com/ARTbio/tools-artbio/tree/master/tools/fetch_fasta_from_ncbi is missing something:

I realized that the "fetch_fasta_from_ncbi" tool is not only retrieving sequences from NCBI nucleotide or protein databases. It also filter this sequences, modifying the header (putting underscores in place of space), eliminating first streches of N that trigger errors on the makeblastdb tools, etc..

Then, Metavisitor user still may wish you upload an use their own fasta sequences. In that case the "sanitization" performed by the Fetch sequences from NCBI tool has to be done in the same way.

Therefore another functionality should be added to the tool: the ability to take as an input a fasta file from the history.

It's tricky because the name of the tool will then be misleading :-/

**Comment by mvdbeek** [comment]
The galaxy way would be to split the functionality in 2:
Fetch seqeunces and sanitize_fasta.

**Comment by drosofff** [comment]
Yes, a mid-term would be to keep the tool as currently is, and to add a
sanitize_fasta for uploded fasta file...

Christophe Antoniewski

ARTbio <http://artbio.fr/> - Tel +33 1 44 2*7 70 05*
Drosophila Genetics & Epigenetics <http://drosophile.org/> - Tel +33 1 44 2
*7 34 39*Mobile +33 6 68 60 51 50
https://twitter.com/ARTbio_IBPS
https://twitter.com/drosofff

2016-04-07 13:19 GMT+02:00 Marius van den Beek <notifications@github.com>:

**Comment by drosofff** [comment]
Well I realize that it a lot of buzz for not much:
User have just to manipulate their fasta headers so that they do not
contain space characters. In some cases it can even work with space. We can
fix the problem with a bit of documentation.

What is as important is that de novo contigs in the Metavisitor workflows
do not contain spaces in their fasta headers.

The general problem is that makeblastdb cuts headers at first space
character, whereas the metavisitor blast parser tool does not.


Christophe Antoniewski

ARTbio <http://artbio.fr/> - Tel +33 1 44 2*7 70 05*
Drosophila Genetics & Epigenetics <http://drosophile.org/> - Tel +33 1 44 2
*7 34 39*Mobile +33 6 68 60 51 50
https://twitter.com/ARTbio_IBPS
https://twitter.com/drosofff

2016-04-07 13:21 GMT+02:00 Christophe Antoniewski <drosofff@gmail.com>:

**Comment by drosofff** [comment]
Closing this issue, follow up in #82
