### ISSUE TITLE
element.identifier does not seem to work with the Galaxy branch release_16.01

### ISSUE THREAD

**Issue by drosofff** [ARTbio/tools-artbio#81]
and as a result, merge output of metavisitor workflows 3-1, 3-2 and 3-3 are not really usable...
Any suggestion ?

**Comment by drosofff** [comment]
Yes I see that https://github.com/galaxyproject/galaxy/pull/1693 is still not merged and in the dev branch, right ?

**Comment by mvdbeek** [comment]
The PR is in 16.04 and dev, normally this should work on 16.04. Also I suppose `element.identifier` is a typo, right? It sould be element_identifier. But are you sure this is why it's not working?
From the issue that the PR addresses:
```
This works fine in most cases, except when running a workflow on a dataset collection that has been moved to a new/different history.
```

I think there was another problem with repeat sections and element_identifiers:
https://github.com/galaxyproject/galaxy/pull/2029

So we could just cherry-pick those changes onto 16.01, or we can move forward to release_16.04, which I think is a more subtle upgrade compared to 15.10 -> 16.01, and we're running this on plastispi for around ~2 weeks without problems.

**Comment by drosofff** [comment]
Yes, it's a typo. I am just rerunning workflows that used to work when I
prepared metavisitor manuscript.
I remember there was an issue with data manager and 16.04 (?). How is this
fixed ?

Christophe Antoniewski

ARTbio <http://artbio.fr/> - Tel +33 1 44 2*7 70 05*
Drosophila Genetics & Epigenetics <http://drosophile.org/> - Tel +33 1 44 2
*7 34 39*Mobile +33 6 68 60 51 50
https://twitter.com/ARTbio_IBPS
https://twitter.com/drosofff

2016-05-08 17:28 GMT+02:00 Marius van den Beek <notifications@github.com>:

**Comment by mvdbeek** [comment]
> Yes, it's a typo. I am just rerunning workflows that used to work when I
> prepared metavisitor manuscript.
> I remember there was an issue with data manager and 16.04 (?). How is this
> fixed ?

So the datamanager issue was solved by upgrading to the latest commit in 16.01.
And that has overwritten the cherry-picked changes in the 2 PRs that concern element_identifiers.
This is the problem with cherry-picking stuff :/. We should probably create our own release branches and regularly PR changes from upstream galaxy into our branch.

**Comment by drosofff** [comment]
OK, I see.
But what i am trying to finalize here is a ansible and docker release of metavisitor that work as announced in the doc. So, in short, is a Galaxy version 16.04 compatible with both data manager ok and element_identifier working with copied histories ?

**Comment by mvdbeek** [comment]
This works now, right? Feel free to reopen if not.
