### ISSUE TITLE
Process of a metavisitor tool upgrade

### ISSUE THREAD

**Issue by drosofff** [ARTbio/tools-artbio#83]
@mvdbeek @JuPeg I wish to review with you the process implied by upgrading a tool of the metavisitor suite, such as PR #80. 

Thus, I see this:
1. Update of a metavisitor tool in https://github.com/ARTbio/tools-artbio.git
2. Pull request accepted in https://github.com/ARTbio/tools-artbio.git
3. Planemo update of the tool
4. Update of the suite_metavisitor_x_y in https://github.com/ARTbio/tools-artbio.git
5. Pull request accepted in https://github.com/ARTbio/tools-artbio.git
6. Planemo update of the suite_metavisitor
7. Update of ansible-artimed/extra-files/metavisitor/metavisitor_tool_list.yml in https://github.com/ARTbio/ansible-artimed.git
8. Pull request accepted in https://github.com/ARTbio/ansible-artimed.git
9. Rebuild a new docker image and push to docker hub

Am I forgetting something ?

**Comment by mvdbeek** [comment]
> Pull request accepted in https://github.com/ARTbio/tools-artbio.git

planemo test should be obligatory here, and a test on real data (successful planemo test -> update plastisipi)

> Rebuild a new docker image and push to docker hub

This should be followed by running the new docker image and generating an updated workflow with the new tool version.

Else it looks good, I think we can put this in a Procedures.md document in this repo.
